### ISSUE TITLE
Files?

### ISSUE THREAD

**Issue by K0-RR** [emilcarr/fabric-sneakhold#1]
![image](https://user-images.githubusercontent.com/43277609/110450329-64059e80-80c3-11eb-99c2-d3e0db9a359b.png)

**Comment by emilcarr** [comment]
Having an issue with curseforge where no file I upload appears due to being marked a duplicate. For now you can download from the [Github Releases page](https://github.com/emilcarr/fabric-sneakhold/releases)

**Comment by srnyx** [comment]
@emilcarr Can you try uploading again?
